### ISSUE TITLE
Review and improve styles (public pages)

### ISSUE THREAD

**Issue by shayanzamiri** [Tarhche/backend#6]
### Description
we need to review the website pages to fix potential bugs and improve styles.

### Acceptance criteria
- public pages should be reviewed and potential bugs should be fixed
- unused css/scss styles should be removed

### Technical notes
- The code blocks are initially from right to left, and when they are fully loaded, they are folded to the left!
- Paragraphs and headings should be spaced
   - if you change a css/scss style, make sure it doesn't have any side effects on other pages.

**Comment by shayanzamiri** [comment]
1- pages/index.vue fixed

**Comment by khanzadimahdi** [comment]
I close this due to moving to using Reactjs / Nextjs.
